# Generated by Django 3.2 on 2023-03-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('detalls', models.TextField(blank=True, null=True)),
                ('ciutat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('cognom1', models.CharField(max_length=50)),
                ('cognom2', models.CharField(max_length=50)),
                ('detalls', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('detalls', models.TextField(null=True)),
                ('inici', models.DateField()),
                ('final', models.DateField()),
                ('equips', models.ManyToManyField(to='lliga.Equip')),
            ],
        ),
        migrations.CreateModel(
            name='Partit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalls', models.TextField(blank=True, null=True)),
                ('lliga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lliga.lliga')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partits_local', to='lliga.equip')),
                ('visitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partits_visitant', to='lliga.equip')),
            ],
        ),
        migrations.CreateModel(
            name='Fitxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inici', models.DateField()),
                ('final', models.DateField(blank=True, null=True)),
                ('equip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lliga.equip')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lliga.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.TimeField(auto_now=True)),
                ('tipus', models.CharField(choices=[('GOL', 'Gol'), ('AUTOGOL', 'Autogol'), ('FALTA', 'Falta'), ('PENALTY', 'Penalty'), ('MANS', 'Mans'), ('CESSIO', 'Cessio'), ('FORA_DE_JOC', 'Fora De Joc'), ('ASSISTENCIA', 'Assistencia'), ('TARGETA_GROGA', 'Targeta Groga'), ('TARGETA_VERMELLA', 'Targeta Vermella')], max_length=30)),
                ('detalls', models.TextField(blank=True, null=True)),
                ('equip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lliga.equip')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='lliga.jugador')),
                ('jugador2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events2', to='lliga.jugador')),
                ('partit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lliga.partit')),
            ],
        ),
    ]
