# Generated by Django 3.2 on 2023-03-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitxa',
            name='dorsal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lliga',
            name='detalls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='partit',
            unique_together={('local', 'visitant', 'lliga')},
        ),
    ]
