# Generated by Django 3.2 on 2023-03-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0003_auto_20230310_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='jugador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_fets', to='lliga.jugador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='jugador2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_rebuts', to='lliga.jugador'),
        ),
    ]
